version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://majd:asal123@ds121716.mlab.com:21716/hotel-users
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     

